- README.md
> Update readme according to new ballerina syntax

- README.md
- component/pom.xml
- pom.xml
Update transport dependency and readme.
> Update transport dependency

- README.md
- component/pom.xml
- component/src/main/ballerina/ballerina/net/fs/natives.bal
- component/src/main/ballerina/ballerina/net/ftp/natives.bal
- component/src/main/java/org/ballerinalang/net/StandardExtensionPackageRepositoryProvider.java
- component/src/main/java/org/ballerinalang/net/fs/server/BallerinaLocalFileSystemListener.java
- component/src/main/java/org/ballerinalang/net/fs/server/LocalFileSystemServerConnectorFutureListener.java
- component/src/main/java/org/ballerinalang/net/ftp/nativeimpl/util/FTPConstants.java
- component/src/main/java/org/ballerinalang/net/ftp/server/BallerinaFTPFileSystemListener.java
- component/src/main/java/org/ballerinalang/net/ftp/server/FTPConnectorFutureListener.java
- component/src/test/java/org/ballerinalang/net/ftp/nativeimpl/FTPClientConnectorTest.java
- component/src/test/resources/test-src/fs/file-system.bal
- component/src/test/resources/test-src/ftp/positive-client-connector-actions.bal
- component/src/test/resources/test-src/ftp/remote-system.bal
- component/src/test/resources/testng.xml
- pom.xml
Add new Ballerina syntax and Connector API changes.
> Add API changes and ballerina syntax  changes

- pom.xml
Add necessary changes that require to Jenkins release process.
> Add release related changes

- component/src/main/java/org/ballerinalang/net/fs/navtiveimpl/Move.java
- component/src/main/java/org/ballerinalang/net/fs/server/LocalFileSystemServerConnector.java
- component/src/main/java/org/ballerinalang/net/ftp/server/FTPServerConnector.java
- component/src/test/java/org/ballerinalang/net/fs/server/LocalFileSystemServerConnectorTest.java
- component/src/test/java/org/ballerinalang/net/ftp/server/FTPServerConnectorTest.java
- pom.xml
Make file-connector up-to-date with latest ballerina version
Upgrading ballerina version from 0.95.0 to 0.95.5
Fixing issues occur due to API changes in BallerinaServerConnector and BServiceUtil API in ballerina 0.95.5
Updated properties relevant to ballerina version
Removed/Modified API usages to match with the current status of Ballerina APIs
Please note that service un-registration has been removed in Ballerina 0.95.5. For the moment that doesn't break file-connector but we need to discuss and decide whether we will be needing that functionality.
N/A
Upgrading ballerina version to 0.95.5
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
Linux 14.04, JDK8
N/A
> Fix issues occurring after ballerina version upgrade

- component/src/main/java/org/ballerinalang/net/fs/server/LocalFileSystemServerConnector.java
- component/src/main/java/org/ballerinalang/net/ftp/server/FTPServerConnector.java
- pom.xml
Ballerina Team has removed the getAnnotation method from the Service API. Therefore Fixing the mentioned getAnnotation method usages in the file and ftp connector.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief …
> Fix getAnnotation method usages

- README.md
- component/pom.xml
- pom.xml
Update version to reflect the API change
> Update version to reflect the API change

- component/src/test/java/org/ballerinalang/net/ftp/nativeimpl/FTPClientConnectorTest.java
> Fix formatting

- README.md
- component/src/main/ballerina/ftp/client_action.bal
- component/src/main/ballerina/ftp/client_endpoint.bal
- component/src/main/ballerina/ftp/listener_endpoint.bal
- component/src/main/java/org/ballerinalang/ftp/client/actions/AbstractFtpAction.java
- component/src/main/java/org/ballerinalang/ftp/client/actions/Append.java
- component/src/main/java/org/ballerinalang/ftp/client/actions/Delete.java
- component/src/main/java/org/ballerinalang/ftp/client/actions/Get.java
- component/src/main/java/org/ballerinalang/ftp/client/actions/IsDirectory.java
- component/src/main/java/org/ballerinalang/ftp/client/actions/List.java
- component/src/main/java/org/ballerinalang/ftp/client/actions/Mkdir.java
- component/src/main/java/org/ballerinalang/ftp/client/actions/Put.java
- component/src/main/java/org/ballerinalang/ftp/client/actions/Rename.java
- component/src/main/java/org/ballerinalang/ftp/client/actions/Rmdir.java
- component/src/main/java/org/ballerinalang/ftp/client/actions/Size.java
- component/src/main/java/org/ballerinalang/ftp/server/FTPFileSystemListener.java
- component/src/main/java/org/ballerinalang/ftp/server/endpoint/Poll.java
- component/src/main/java/org/ballerinalang/ftp/util/FtpConstants.java
- component/src/test/resources/test-src/positive-client-connector-actions.bal
- pom.xml
Resolves https://github.com/wso2-ballerina/package-file/issues/35, https://github.com/wso2-ballerina/package-file/issues/33, https://github.com/wso2-ballerina/package-file/issues/34
> Update the ballerina version and improve error logging

- README.md
- component/src/main/ballerina/ftp/client_endpoint.bal
- component/src/main/ballerina/ftp/commons.bal
- component/src/main/ballerina/ftp/error.bal
- component/src/main/ballerina/ftp/file_event.bal
- component/src/main/ballerina/ftp/listener_endpoint.bal
- component/src/test/resources/test-src/positive-client-connector-actions.bal
- pom.xml
> Update the ballerina version

- README.md
- component/pom.xml
- component/src/main/ballerina/ftp/client_endpoint.bal
- component/src/main/ballerina/ftp/commons.bal
- component/src/main/ballerina/ftp/error.bal
- component/src/main/ballerina/ftp/file_event.bal
- component/src/main/ballerina/ftp/listener_endpoint.bal
- component/src/test/resources/test-src/positive-client-connector-actions.bal
- pom.xml
> Update ballerina version

- README.md
- component/src/main/ballerina/ftp/Module.md
- component/src/main/java/org/ballerinalang/ftp/client/actions/Append.java
- component/src/main/java/org/ballerinalang/ftp/client/actions/Delete.java
- component/src/main/java/org/ballerinalang/ftp/client/actions/Get.java
- component/src/main/java/org/ballerinalang/ftp/client/actions/IsDirectory.java
- component/src/main/java/org/ballerinalang/ftp/client/actions/List.java
- component/src/main/java/org/ballerinalang/ftp/client/actions/Mkdir.java
- component/src/main/java/org/ballerinalang/ftp/client/actions/Put.java
- component/src/main/java/org/ballerinalang/ftp/client/actions/Rename.java
- component/src/main/java/org/ballerinalang/ftp/client/actions/Rmdir.java
- component/src/main/java/org/ballerinalang/ftp/client/actions/Size.java
- component/src/main/java/org/ballerinalang/ftp/client/endpoint/InitEndpoint.java
- component/src/main/java/org/ballerinalang/ftp/server/endpoint/Register.java
- component/src/main/java/org/ballerinalang/ftp/util/FTPUtil.java
- component/src/test/java/org/ballerinalang/ftp/client/FTPClientConnectorTest.java
- component/src/test/resources/test-src/positive-client-connector-actions.bal
Fix issue #47
Issue caused by username or password contains certain characters. Those characters can't appear in their raw form in the username and password fields.So they will make the invalid URI.
I made the changes in the createUrl method and related files
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
> Refactor the connector

- Ballerina.lock
- Ballerina.toml
- compiler-plugin/pom.xml
- pom.xml
- utils/wso2-ftp/pom.xml
- utils/wso2-ftp/src/main/java/org/wso2/ei/ftp/util/FtpConstants.java
Upgraded FTP connector version to 0.3.0
> Upgraded FTP connector version to 0.3.0

- src/ftp/client_endpoint.bal
- src/ftp/commons.bal
- src/ftp/external_functions.bal
- src/ftp/listener_endpoint.bal
- src/ftp/tests/client_endpoint_test.bal
- utils/wso2-ftp/src/main/java/org/wso2/ei/ftp/client/FTPClient.java
- utils/wso2-ftp/src/main/java/org/wso2/ei/ftp/client/FTPClientHelper.java
- utils/wso2-ftp/src/main/java/org/wso2/ei/ftp/client/FTPClientListener.java
- utils/wso2-ftp/src/main/java/org/wso2/ei/ftp/server/FTPListener.java
- utils/wso2-ftp/src/main/java/org/wso2/ei/ftp/server/FTPListenerHelper.java
- utils/wso2-ftp/src/main/java/org/wso2/ei/ftp/util/FTPConstants.java
- utils/wso2-ftp/src/main/java/org/wso2/ei/ftp/util/FTPUtil.java
- utils/wso2-ftp/src/main/java/org/wso2/ei/testutil/MockFTPServer.java
Modified append and put operations to support text, xml, JSON and file inputs.
> Modified append and put operations

- src/ftp/Module.md
- src/ftp/client_endpoint.bal
- src/ftp/listener_endpoint.bal
> Modified Module.md

- ftp-compiler-plugin/pom.xml
- ftp-utils/pom.xml
- ftp/Ballerina.toml
- ftp/pom.xml
- pom.xml
> Updated module version

- ftp-compiler-plugin/pom.xml
- ftp-utils/pom.xml
- ftp/pom.xml
- pom.xml
> Fixed license header issues

- .travis.yml
- ftp-compiler-plugin/pom.xml
- ftp-utils/pom.xml
- ftp-utils/src/main/java/org/wso2/ei/b7a/ftp/core/client/FTPClientHelper.java
- ftp-utils/src/main/java/org/wso2/ei/b7a/ftp/core/server/FTPListener.java
- ftp-utils/src/main/java/org/wso2/ei/b7a/ftp/core/util/FTPConstants.java
- ftp/Ballerina.lock
- ftp/Ballerina.toml
- ftp/pom.xml
- pom.xml
Migrating FTP Connector to Ballerina 1.1.0.
This PR contains syntax changes which is compatible with Ballerina 1.1.0.
> Migration to Ballerina 1.1.0

- ftp-compiler-plugin/pom.xml
- ftp-utils/pom.xml
- ftp-utils/src/main/java/org/wso2/ei/b7a/ftp/core/util/FTPConstants.java
- ftp/Ballerina.lock
- ftp/Ballerina.toml
- ftp/pom.xml
- ftp/src/ftp/Module.md
- pom.xml
This PR will update the FTP module version.
> Upgrade FTP module version

- README.md
- ftp-compiler-plugin/pom.xml
- ftp-utils/pom.xml
- ftp-utils/src/main/java/org/wso2/ei/b7a/ftp/core/util/FTPConstants.java
- ftp/Ballerina.lock
- ftp/Ballerina.toml
- ftp/pom.xml
- ftp/src/ftp/Module.md
- pom.xml
$title.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …
> Remove unwanted class from packing and version bump

- .github/workflows/ci.yml
- .github/workflows/release.yml
> Update git actions

- README.md
- ftp-compiler-plugin/pom.xml
- ftp-utils/pom.xml
- ftp-utils/src/main/java/org/wso2/ei/b7a/ftp/core/util/FTPConstants.java
- ftp-utils/src/main/java/org/wso2/ei/b7a/ftp/core/util/FTPUtil.java
- ftp/Ballerina.lock
- ftp/Ballerina.toml
- ftp/pom.xml
- ftp/src/ftp/Module.md
- ftp/src/ftp/client_endpoint.bal
- ftp/src/ftp/external_functions.bal
- ftp/src/ftp/listener_endpoint.bal
- ftp/src/ftp/tests/client_endpoint_test.bal
- pom.xml
> Change ballerina organization to `ballerina` from `wso2` and update the code to compatible with Ballerina 1.2.0 release.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link …
> Change ballerina organization and bump the version

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .travis.yml
- ftp/pom.xml
- pom.xml
> Remove SNAPSHOT version

- .travis.yml
- README.md
- ftp-compiler-plugin/pom.xml
- ftp-utils/pom.xml
- ftp-utils/src/main/java/org/wso2/ei/b7a/ftp/core/client/FTPClient.java
- ftp-utils/src/main/java/org/wso2/ei/b7a/ftp/core/client/FTPClientHelper.java
- ftp-utils/src/main/java/org/wso2/ei/b7a/ftp/core/server/FTPListener.java
- ftp-utils/src/main/java/org/wso2/ei/b7a/ftp/core/server/FTPListenerHelper.java
- ftp-utils/src/main/java/org/wso2/ei/b7a/ftp/core/util/FTPConstants.java
- ftp-utils/src/main/java/org/wso2/ei/b7a/ftp/core/util/FTPUtil.java
- ftp-utils/src/main/java/org/wso2/ei/b7a/ftp/testutil/MockFTPServer.java
- ftp/Ballerina.lock
- ftp/Ballerina.toml
- ftp/pom.xml
- ftp/src/ftp/Module.md
- ftp/src/ftp/client_endpoint.bal
- ftp/src/ftp/listener_endpoint.bal
- ftp/src/ftp/tests/client_endpoint_test.bal
- pom.xml
Migrate FTP connector to Ballerina 2.0.0. Resolves 101.
> Migrate to Ballerina Swan Lake

- README.md
Link badge links and issue links to new stdlib repository.
> Link README to new Stdlib repo

- README.md
> Improve issues and projects description

- ftp-native/build.gradle
Remove incorrectly packed stdlibs from deprecated locations.
> Remove ballerina-lang dependent Stdlibs

- README.md
> Remove unimplemented BBE link

- ftp-ballerina/src/ftp/listener_endpoint.bal
- ftp-native/src/main/java/org/ballerinalang/stdlib/ftp/util/FTPConstants.java
- gradle.properties
Update FTP module to a new version with new dependency versions.
> Migrate FTP module to 1.0.1

- ftp-native/build.gradle
- ftp-native/src/main/java/module-info.java
- ftp-native/src/main/java/org/ballerinalang/stdlib/ftp/service/compiler/FTPCompilerPlugin.java
> Update Diagnostic API changes

- .github/workflows/build-master.yml
- .github/workflows/pull-request.yml
$subject related to ballerina-platform/ballerina-standard-library#569
> Update secrets related to PR build

- ftp-native/src/main/java/org/ballerinalang/stdlib/ftp/client/FTPClient.java
- ftp-native/src/main/java/org/ballerinalang/stdlib/ftp/client/FTPClientHelper.java
- ftp-native/src/main/java/org/ballerinalang/stdlib/ftp/server/FTPListener.java
- ftp-native/src/main/java/org/ballerinalang/stdlib/ftp/server/FTPListenerHelper.java
- ftp-native/src/main/java/org/ballerinalang/stdlib/ftp/util/FTPUtil.java
- ftp-test-utils/src/main/java/org/ballerinalang/stdlib/ftp/testutils/mockServerUtils/MockFTPServer.java
Migrate ballerina runtime APIs.
> Migrate ballerina runtime APIs

- ftp-ballerina/tests/listener_endpoint_test.bal
Fix intermittent test failures by guaranteed WatchEvent at the listener.
> Fix intermittent test failures by guaranteed WatchEvent at the listener

- ftp-test-utils/build.gradle
- ftp-test-utils/src/main/java/module-info.java
> Remove unnecessary test dependencies

- ftp-native/src/main/java/org/ballerinalang/stdlib/ftp/util/FTPConstants.java
- gradle.properties
Sync master after 1.0.2 release.
> Sync master after 1.0.2 release

- ftp-ballerina/Package.md
- ftp-ballerina/listener_endpoint.bal
- ftp-ballerina/tests/client_endpoint_test.bal
- ftp-ballerina/tests/listener_endpoint_test.bal
> Migrate to new log module APIs

- ftp-ballerina/Package.md
> Update module description to follow the convention

- ftp-ballerina/init.bal
- ftp-native/src/main/java/org/ballerinalang/stdlib/ftp/client/FTPClientHelper.java
- ftp-native/src/main/java/org/ballerinalang/stdlib/ftp/server/FTPListener.java
- ftp-native/src/main/java/org/ballerinalang/stdlib/ftp/util/FTPConstants.java
- ftp-native/src/main/java/org/ballerinalang/stdlib/ftp/util/FTPUtil.java
- ftp-native/src/main/java/org/ballerinalang/stdlib/ftp/util/ModuleUtils.java
> Remove hard coded ballerina version in java code
> Remove hard coded ballerina version in java code

- ftp-native/src/main/java/org/ballerinalang/stdlib/ftp/server/FTPListener.java
> Update Ballerina lang API changes

- build.gradle
- ftp-ballerina/Ballerina.toml
- ftp-ballerina/build.gradle
- ftp-ballerina/tests/listener_endpoint_test.bal
- gradle.properties
> Migrate runtime:sleep to lang.runtime:sleep

- ftp-ballerina/tests/client_endpoint_test.bal
> Fix testerina function configs

- ftp-ballerina/listener_endpoint.bal
> Update Scheduler API change

- ftp-ballerina/build.gradle
Update ballerina command to bal command
issue https://github.com/ballerina-platform/ballerina-lang/issues/27680#issuecomment-761567108
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc …
> Update ballerina command to bal command

- ftp-ballerina/client_endpoint.bal
- ftp-ballerina/external_functions.bal
- ftp-ballerina/init.bal
- ftp-ballerina/listener_endpoint.bal
- ftp-ballerina/tests/client_endpoint_test.bal
Related Issue: ballerina-platform/ballerina-lang#28034
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
> Change the name of the `java` langlib module to `jballerina.java`

- ftp-ballerina/Ballerina.toml
- ftp-ballerina/Dependencies.toml
- ftp-ballerina/build.gradle
Fixes ballerina-platform/ballerina-lang#27988
> Add Dependencies.toml

- ftp-ballerina/build.gradle
> Revert dependency toml file after build

- .github/workflows/build-master.yml
- .github/workflows/pull-request.yml
- ftp-ballerina/build.gradle
> Enable checkstyle and spotbugs

- README.md
- ftp-ballerina/Package.md
> Remove swan-lake from URLs

- .github/workflows/publish-release.yml
- build.gradle
- ftp-ballerina/build.gradle
- gradle.properties
> Enable publishing to Ballerina Central during release

- gradle.properties
> Manually update dependency versions

- build.gradle
- ftp-ballerina/build.gradle
> Re-order Build Tasks to Publish to the Ballerina Central

- .github/workflows/pull-request.yml
- gradle.properties
> Correct the version change by automated PR

- ftp-ballerina/build.gradle
> Remove publishing testable jar and exec artifacts

- ftp-ballerina/build.gradle
> Add extracted bala in the zip artifact
> Fixes ballerina-platform/ballerina-lang#27763
> Add extracted bala in the zip artifact

- ftp-ballerina/build.gradle
> Add -c flag to build command
> Related to ballerina-platform/ballerina-lang#29032
> Add -c flag to build command

- build.gradle
- ftp-ballerina/listener_endpoint.bal
- gradle.properties
> Add time module transitive dependency

- ftp-ballerina/client_endpoint.bal
- ftp-ballerina/error.bal
- ftp-ballerina/external_functions.bal
- ftp-ballerina/tests/client_endpoint_test.bal
$subject.
Resolves https://github.com/ballerina-platform/ballerina-standard-library/issues/1112
> Move all error types to a common error type

- ftp-ballerina/Package.md
> Remove non-existing link and correct error types

- build.gradle
- ftp-ballerina/build.gradle
> Strip stdlib dependency version

- ftp-ballerina/build.gradle
Set flag to enable Jacoco Coverage XML generation. Fixes https://github.com/ballerina-platform/ballerina-lang/issues/30381
> Set flag to enable Jacoco Coverage XML generation

- build-config/checkstyle/build.gradle
- build.gradle
- ftp-ballerina/build.gradle
Standardize build script of Ballerina module
> Apply Gradle Ballerina plugin for Ballerina module build script

- ftp-ballerina/build.gradle
- gradle.properties
> Move to stable version of plugin

- ftp-ballerina/tests/client_endpoint_test.bal
> Add re-check for directory after `rmdir` is executed for 10 seconds

- ftp-ballerina/tests/client_endpoint_test.bal
$subject.
Issue is reported in https://github.com/ballerina-platform/ballerina-standard-library/issues/1448
> Disable the intermittent assert statement failure

- ftp-ballerina/Package.md
Relates to ballerina-platform/ballerina-standard-library#1462
> Update Package.md links into HTML format

- ftp-ballerina/Package.md
> Make the Ballerina link be opened in a new tab

- changelog.md
- ftp-ballerina/tests/client_endpoint_negative_test.bal
- ftp-native/src/main/java/org/ballerinalang/stdlib/ftp/client/FtpClient.java
- ftp-native/src/main/java/org/ballerinalang/stdlib/ftp/client/FtpClientHelper.java
- ftp-native/src/main/java/org/ballerinalang/stdlib/ftp/client/FtpClientListener.java
- ftp-native/src/main/java/org/ballerinalang/stdlib/ftp/util/FtpConstants.java
- ftp-native/src/main/java/org/ballerinalang/stdlib/ftp/util/FtpUtil.java
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/1527
> Create module specific error instead of generic Ballerina error

- ftp-ballerina/tests/client_endpoint_negative_test.bal
- ftp-ballerina/tests/client_endpoint_test.bal
- ftp-native/src/main/java/org/ballerinalang/stdlib/ftp/client/FtpClient.java
- ftp-native/src/main/java/org/ballerinalang/stdlib/ftp/client/FtpClientHelper.java
- ftp-native/src/main/java/org/ballerinalang/stdlib/ftp/client/FtpClientListener.java
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/1522 and https://github.com/ballerina-platform/ballerina-standard-library/issues/1448
> Complete balFuture only once

- ftp-ballerina/Module.md
- ftp-ballerina/error.bal
- ftp-ballerina/tests/secure_client_endpoint_test.bal
$subject
Resolves https://github.com/ballerina-platform/ballerina-standard-library/issues/1557 and https://github.com/ballerina-platform/ballerina-standard-library/issues/1556
> Fixes doc bugs and correct a test case

- changelog.md
- ftp-ballerina/Module.md
- ftp-ballerina/commons.bal
- ftp-ballerina/tests/client_endpoint_negative_test.bal
- ftp-ballerina/tests/client_endpoint_test.bal
- ftp-ballerina/tests/listener_endpoint_test.bal
- ftp-ballerina/tests/secure_client_endpoint_test.bal
- ftp-ballerina/tests/secure_listener_endpoint_test.bal
- ftp-native/src/main/java/org/ballerinalang/stdlib/ftp/util/FtpConstants.java
- ftp-native/src/main/java/org/ballerinalang/stdlib/ftp/util/FtpUtil.java
- ftp-test-utils/src/main/java/org/ballerinalang/stdlib/ftp/testutils/mockServerUtils/MockFtpServer.java
Resolves https://github.com/ballerina-platform/ballerina-standard-library/issues/1606
> Rename BasicAuth record to Credentials

- changelog.md
- ftp-ballerina/tests/client_endpoint_test.bal
- ftp-native/src/main/java/org/ballerinalang/stdlib/ftp/util/FtpUtil.java
- ftp-test-utils/src/main/java/org/ballerinalang/stdlib/ftp/testutils/mockServerUtils/MockFtpServer.java
Resolves https://github.com/ballerina-platform/ballerina-standard-library/issues/1607
> Add anonymous FTP

- build.gradle
Relates to https://github.com/ballerina-platform/module-ballerina-ftp/pull/316#issuecomment-878006052
> Correct the project group name

- ballerina/byte_stream.bal
- ballerina/client_endpoint.bal
- ballerina/commons.bal
- ballerina/external_functions.bal
- ballerina/tests/client_endpoint_negative_test.bal
- ballerina/tests/client_endpoint_test.bal
- ballerina/tests/secure_client_endpoint_test.bal
- changelog.md
- native/src/main/java/io/ballerina/stdlib/ftp/client/FtpClient.java
- test-utils/src/main/java/io/ballerina/stdlib/ftp/testutils/mockServerUtils/MockFtpServer.java
Resolves https://github.com/ballerina-platform/ballerina-standard-library/issues/1546
Add more tests and improve the code coverage.
> Improve error handling logic of `get` method

- ballerina/tests/client_endpoint_test.bal
- changelog.md
- test-utils/src/main/java/io/ballerina/stdlib/ftp/testutils/mockServerUtils/MockFtpServer.java
> Add tests to recursive directory removal

- ballerina/client_endpoint.bal
- ballerina/tests/client_endpoint_negative_test.bal
- ballerina/tests/client_endpoint_test.bal
- ballerina/tests/secure_client_endpoint_test.bal
- changelog.md
- native/src/main/java/io/ballerina/stdlib/ftp/client/FtpClient.java
- native/src/main/java/io/ballerina/stdlib/ftp/client/FtpClientHelper.java
- native/src/main/java/io/ballerina/stdlib/ftp/client/FtpClientListener.java
- native/src/main/java/io/ballerina/stdlib/ftp/server/FtpListener.java
- native/src/main/java/io/ballerina/stdlib/ftp/server/FtpListenerHelper.java
- native/src/main/java/io/ballerina/stdlib/ftp/transport/RemoteFileSystemConnectorFactory.java
- native/src/main/java/io/ballerina/stdlib/ftp/transport/client/connector/contract/VfsClientConnector.java
- native/src/main/java/io/ballerina/stdlib/ftp/transport/client/connector/contractimpl/VfsClientConnectorImpl.java
- native/src/main/java/io/ballerina/stdlib/ftp/transport/impl/RemoteFileSystemConnectorFactoryImpl.java
- native/src/main/java/io/ballerina/stdlib/ftp/transport/listener/RemoteFileSystemListener.java
- native/src/main/java/io/ballerina/stdlib/ftp/transport/server/RemoteFileSystemConsumer.java
- native/src/main/java/io/ballerina/stdlib/ftp/transport/server/connector/contract/RemoteFileSystemServerConnector.java
- native/src/main/java/io/ballerina/stdlib/ftp/transport/server/connector/contractimpl/RemoteFileSystemServerConnectorImpl.java
- native/src/main/java/io/ballerina/stdlib/ftp/util/ExcludeCoverageFromGeneratedReport.java
- native/src/main/java/io/ballerina/stdlib/ftp/util/FtpConstants.java
- native/src/main/java/io/ballerina/stdlib/ftp/util/FtpUtil.java
1. Resolves https://github.com/ballerina-platform/ballerina-standard-library/issues/1749
2. Resolves https://github.com/ballerina-platform/ballerina-standard-library/issues/1782
3. Comment test verification for test `testDeleteFileAtNonExistingLocation` due to https://github.com/ballerina-platform/ballerina-standard-library/issues/1789
4. Improve verification in tests
5. Improve test fail messages
6. Improve connection close logic
7. Enable test, `testRemoveComplexDirectory` commenting the verification
8. Remove unwanted method, `validateParam`
9. Add tests for invalid and non-existing file/directory path access
10. Add negative tests for connection creation
11. Rename variables and methods adhering to the convention
12. Add error logs for unhandled exceptions
13. Move common strings to …
> Improve connection initialization logic and cleanup the code base

- ballerina/Module.md
- ballerina/tests/secure_listener_endpoint_test.bal
Relates to https://github.com/ballerina-platform/module-ballerina-ftp/pull/351 and https://github.com/ballerina-platform/module-ballerina-ftp/pull/381
> Update `Module.md` file on API changes

- ballerina/Ballerina.toml
- ballerina/build.gradle
- build.gradle
- gradle.properties
- test-utils/build.gradle
- test-utils/src/main/java/module-info.java
> Remove bouncycastle dependency

- ballerina/Dependencies.toml
- ballerina/tests/listener_endpoint_test.bal
- native/src/main/java/io/ballerina/stdlib/ftp/server/FtpListener.java
- native/src/main/java/io/ballerina/stdlib/ftp/util/FtpConstants.java
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/1937
> Change onFileChange function to a remote function

- ballerina/Dependencies.toml
- gradle.properties
> Fix a dependency related merge build failure

- gradle.properties
> Sync Master After 2.0.0 Release

- .github/workflows/build-timestamped-master.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- .github/workflows/trivy-scan.yml
- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- ballerina/build.gradle
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2033
> Add files using git add before automated commit

- gradle.properties
> Bump org.apache.mina:mina-core dependency version

- ballerina/listener_endpoint.bal
$subject related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2040
> Remove start and stop logs of ftp listener

- ballerina/external_functions.bal
- ballerina/listener_endpoint.bal
- ballerina/tests/listener_endpoint_test.bal
- changelog.md
- gradle.properties
$subject related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2398
> Make FTP service-type distinct

- .github/workflows/publish-release.yml
- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
Related to ballerina-platform/ballerina-standard-library#2426
> Add a cleaning phase to the GitHub release action

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- build.gradle
- gradle.properties
1. $subject
2. Resolves https://github.com/ballerina-platform/ballerina-standard-library/issues/2425
> Update version which was not updated with an automated PR

- examples/file-storage/README.md
> Correct the directory paths of the example

- ballerina/tests/listener_endpoint_test.bal
- native/src/main/java/io/ballerina/stdlib/ftp/server/FtpListener.java
- native/src/main/java/io/ballerina/stdlib/ftp/transport/message/FileInfo.java
- native/src/main/java/io/ballerina/stdlib/ftp/transport/server/RemoteFileSystemConsumer.java
Resolves https://github.com/ballerina-platform/ballerina-standard-library/issues/2528
Resolves https://github.com/ballerina-platform/ballerina-standard-library/issues/2535
> Add missing fields to `ftp:FileInfo`

- ballerina/listener_endpoint.bal
- ballerina/tests/secure_listener_endpoint_test.bal
- changelog.md
- examples/covid19-stat-publisher/processor/processor.bal
- native/src/main/java/io/ballerina/stdlib/ftp/client/FtpClient.java
- native/src/main/java/io/ballerina/stdlib/ftp/server/FtpListenerHelper.java
- native/src/main/java/io/ballerina/stdlib/ftp/util/FtpConstants.java
- native/src/main/java/io/ballerina/stdlib/ftp/util/FtpUtil.java
1. Resolves https://github.com/ballerina-platform/ballerina-standard-library/issues/2549
2. Add a new constant to the key path.
> Make two config fields optional

- ballerina/build.gradle
> Remove unused docker run from gradle

- load-tests/ftp_pubsub/src/main.bal
> Increase load test time

- ballerina/Module.md
- ballerina/client_endpoint.bal
- ballerina/listener_endpoint.bal
- docs/spec/spec.md
$subject
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2202
> Add FTP specification

- ballerina/Dependencies.toml
- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/ftp/plugin/FtpServiceValidationTest.java
- compiler-plugin-tests/src/test/resources/ballerina_sources/invalid_service_16/Ballerina.toml
- compiler-plugin-tests/src/test/resources/ballerina_sources/invalid_service_16/service.bal
- compiler-plugin-tests/src/test/resources/ballerina_sources/invalid_service_17/Ballerina.toml
- compiler-plugin-tests/src/test/resources/ballerina_sources/invalid_service_17/service.bal
- compiler-plugin-tests/src/test/resources/ballerina_sources/invalid_service_18/Ballerina.toml
- compiler-plugin-tests/src/test/resources/ballerina_sources/invalid_service_18/service.bal
- compiler-plugin/src/main/java/io/ballerina/stdlib/ftp/plugin/FtpFunctionValidator.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/ftp/plugin/PluginUtils.java
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2785
& this improves the function validation logic in several places
> Fix compiler plugin validation invalid error

- ballerina/Dependencies.toml
- ballerina/tests/listener_endpoint_test.bal
$subject
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1967
> Add a test to validate deleted files from the FTP listener

- .github/workflows/central-publish.yml
- .github/workflows/publish-release.yml
- .github/workflows/trivy-scan.yml
- native/build.gradle
- native/src/main/java/io/ballerina/stdlib/ftp/util/BufferHolder.java
- native/src/main/java/module-info.java
$subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2802
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2902
> Change the scan type of the Trivy scan and remove core usage

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- build-config/resources/Ballerina.toml
- gradle.properties
$subject
Related to [`Update std libs with 2201.2.0 lang version #3128`](https://github.com/ballerina-platform/ballerina-standard-library/issues/3128)
> Migrate to update 2

- README.md
- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- ballerina/Package.md
- build-config/resources/Ballerina.toml
- changelog.md
- docs/spec/spec.md
- gradle.properties
$subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3463
> Replace slack channel link with discord server link and update lang versions

- .github/workflows/build-with-bal-test-native.yml
- README.md
- gradle.properties
Part of : https://github.com/ballerina-platform/ballerina-standard-library/issues/3316
> Add native build workflow

- native/src/main/resources/META-INF/native-image/io.ballerina.stdlib/ftp-native/reflect-config.json
- native/src/main/resources/META-INF/native-image/io.ballerina.stdlib/ftp-native/resource-config.json
> [Test] Add missing configs

- native/src/main/resources/META-INF/native-image/io.ballerina.stdlib/ftp-native/reflect-config.json
- native/src/main/resources/META-INF/native-image/io.ballerina.stdlib/ftp-native/resource-config.json
> Add missing configs for native image

- ballerina/tests/secure_listener_endpoint_with_caller_test.bal
- native/src/main/java/io/ballerina/stdlib/ftp/server/FtpListener.java
> Add referred type support

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- build-config/resources/Ballerina.toml
- gradle.properties
- native/src/main/java/io/ballerina/stdlib/ftp/server/FtpListener.java
- native/src/main/java/io/ballerina/stdlib/ftp/util/FtpUtil.java
$subject
https://github.com/ballerina-platform/ballerina-standard-library/issues/3517
> Fix failing build for type reference support

- ballerina/Dependencies.toml
- gradle.properties
$subject
https://github.com/ballerina-platform/ballerina-standard-library/issues/3517
> Update versions for type-reference-support 

- ballerina/Ballerina.toml
- ballerina/init.bal
- native/src/main/java/io/ballerina/stdlib/ftp/util/ModuleUtils.java
- native/src/main/java/module-info.java
- native/src/main/resources/logging.properties
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3698
> Remove native logs from appearing

- ballerina/Ballerina.toml
- build-config/resources/Ballerina.toml
> Remove testng from dependencies

- ballerina/build.gradle
- test-utils/build.gradle
- test-utils/src/main/java/module-info.java
> Remove testng dependency

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- gradle.properties
> Bump to next patch version

- ballerina/Ballerina.toml
- build-config/resources/Ballerina.toml
$subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3843
> Add artifact and group ids in Ballerina.toml

- native/src/main/resources/META-INF/native-image/io.ballerina.stdlib/ftp-native/resource-config.json
> Add missing native config

- native/src/main/resources/META-INF/native-image/io.ballerina.stdlib/ftp-native/resource-config.json
> [master] Add missing native config

- .github/workflows/build-timestamped-master.yml
- .github/workflows/pull-request.yml
- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- codecov.yml
- compiler-plugin-tests/build.gradle
- gradle.properties
$subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/4195
> Add code coverage for compiler plugin

- examples/covid19-stat-publisher/README.md
> Update meta information of examples

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- native/src/main/java/io/ballerina/stdlib/ftp/server/FtpListener.java
- native/src/main/java/io/ballerina/stdlib/ftp/util/FtpUtil.java
This is to support the build for https://github.com/ballerina-platform/ballerina-standard-library/issues/4344
> Fix object getType() API usage

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- changelog.md
- native/src/main/java/io/ballerina/stdlib/ftp/util/FtpConstants.java
- native/src/main/java/io/ballerina/stdlib/ftp/util/ModuleUtils.java
- native/src/main/resources/META-INF/native-image/io.ballerina.stdlib/ftp-native/resource-config.json
- native/src/main/resources/ftp_logging.properties
$subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/4478
Tested the sample in the issue. Logs work as expected.
> Update the method used to stop the native level logs

- examples/covid19-stat-publisher/sftp-server/build.gradle
- gradle.properties
> Update required dependency versions for Java 17 migration

- ballerina/build.gradle
- build.gradle
- gradle.properties
- test-utils/build.gradle
> Fix issues with jcraft JSch version

- .github/workflows/build-with-bal-test-graalvm.yml
> Change lang tag for graalvm build

- .github/workflows/build-with-bal-test-graalvm.yml
> Change GraalVm build to java 17

- changelog.md
- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/ftp/plugin/CodeSnippetGenerationCodeActionTest.java
- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/ftp/plugin/FtpServiceValidationTest.java
- compiler-plugin-tests/src/test/resources/ballerina_sources/valid_service_6/Ballerina.toml
- compiler-plugin-tests/src/test/resources/ballerina_sources/valid_service_6/service.bal
- compiler-plugin/src/main/java/io/ballerina/stdlib/ftp/plugin/FtpServiceValidator.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/ftp/plugin/PluginConstants.java
- native/src/main/java/io/ballerina/stdlib/ftp/server/FtpListenerHelper.java
$subject
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/4741
> Update compiler plugin to allow annotations

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- ballerina/commons.bal
- ballerina/tests/client_endpoint_test.bal
- gradle.properties
- native/src/main/java/io/ballerina/stdlib/ftp/client/FtpClient.java
- native/src/main/java/io/ballerina/stdlib/ftp/transport/server/util/FileTransportUtils.java
- native/src/main/java/io/ballerina/stdlib/ftp/util/FtpConstants.java
Fixes: https://github.com/ballerina-platform/ballerina-library/issues/6768
> Support preferred auth methods in SFTP client initialization

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- build-config/resources/Ballerina.toml
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
> Update dependency versions for Update 11
